### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by gj1118** [davidbwaters/High-Sienna#1]
I am seeing this issue 

<img width="587" alt="image" src="https://user-images.githubusercontent.com/473101/42422732-bdbe9fa4-82b9-11e8-8b24-54da26d8ce5d.png">

apparently it seems some of the resources are not present in the package !

**Comment by EivindArvesen** [comment]
I'm seeing this as well.

I'm also getting this error:

![skjermbilde 2018-07-10 kl 14 29 46](https://user-images.githubusercontent.com/939844/42509984-dae27a16-844d-11e8-954a-dba062e59f19.png)

It seems there are some dependencies to `Theme - Sienna` that aren't handled automatically or documented.

**Comment by davidbwaters** [comment]
Sorry for taking so long to get to this.  Should be fixed.  It was a naming issue with the Package Control version.

**Comment by davidbwaters** [comment]
I've tested and not having problems.  Closing this.
